### ISSUE TITLE
Notifications: Investigate Exception From `getChain`

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/l2-flexible-voting-frontend#84]
<img width="1009" alt="Screen Shot 2023-10-30 at 9 55 02 PM" src="https://github.com/ScopeLift/l2-flexible-voting-frontend/assets/1479802/1eeeaa0b-d436-481c-b639-7281524f1284">

**Comment by garyghayrat** [comment]
After investigating, found out that this occurs when a user switches networks after bridging from l1 to l2 or vice versa without clearing notifications (one pending tx notification and one successful tx notification).

My guess is that when the network changes, `useWaitForTransaction` is called again. https://github.com/ScopeLift/l2-flexible-voting-frontend/blob/8cffc9e6c872a18957a7d811bae84954f1949a72/hooks/useEasyWrite.ts#L25C2-L33
which triggers new `notify` functions because of the `useEffect` dependencies in the same file: https://github.com/ScopeLift/l2-flexible-voting-frontend/blob/8cffc9e6c872a18957a7d811bae84954f1949a72/hooks/useEasyWrite.ts#L87-L96 The new notification needs a new `Notification` component https://github.com/ScopeLift/l2-flexible-voting-frontend/blob/8cffc9e6c872a18957a7d811bae84954f1949a72/components/Notifications.tsx#L64 which requires a `chainId` to get the chain name using `getChain`. And that in turn throws the error in the screenshot,
https://github.com/ScopeLift/l2-flexible-voting-frontend/blob/8cffc9e6c872a18957a7d811bae84954f1949a72/util/index.ts#L23
 because from `console.log`s, it seems like the `chainId` is `undefined` during the moment when the network is switching.
